### ISSUE TITLE
Move (atleast the) kernel patches in cc-oci-runtime to this repo

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#12]
https://github.com/01org/cc-oci-runtime/tree/master/data/obs-packaging contains, amongst other things, the set of kernel patches applied to the guest kernel.

Now that we have two runtimes using the same kernel, it makes sense to move (atleast) the kernel patches to the `packaging` repo so the data can be shared more easily.

It may make sense to move the entire `obs-packaging` folder into the `packaging` repo?

**Comment by gorozco1** [comment]
yes.. it makes sense to move to this project...

cc2.1 and cc3.0 share the kernel, the image, qemu-lite and selinux modules to start proxy
