### ISSUE TITLE
Building from a commit replaces version

### ISSUE THREAD

**Issue by erick0z** [clearcontainers/packaging#124]
When building from a specific branch or commit, the version gets replaced in the templates, so the OBS _service file will know from where retrieve a source tarball. The problem is that all the VERSION string gets replaced in the remaining templates so  a package gets created with a wrong version number. example: `cc-proxy-28b5af4+git.28b5af4-6.1`. In this case the version got replaced by the short form of the commit ID.

**Comment by erick0z** [comment]
The best solution is to never replace @PARENT_TAG@ from the _service file, so OBS will use the latest release, plus the latest commit ID. e.g. cc-runtime-3.0.0+git.<LATEST_COMMIT_ID>-6.1. @gorozco1 what do you think?

**Comment by gorozco1** [comment]
@erick0z agree
