### ISSUE TITLE
Add apport hook for Ubuntu packages

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#135]
[source_cc-runtime.py.txt](https://github.com/clearcontainers/packaging/files/1358686/source_cc-runtime.py.txt)

To make it easier for users to report problems, we should add an apport hook to the following Ubuntu packages:

- `cc-proxy`
- `cc-runtime`
- `cc-shim`
- `qemu-lite`

I've attached the basic hook which will call the `cc-collect-data.sh` script when any of the components above crashes. The script output will then be added to the standard Ubuntu bug report that will get created on launchpad.net.

The hook needs to be installed on Ubuntu systems only to the following directory:

```
/usr/share/apport/package-hooks/
```
The name of the hook is also important. The format we need to use is `source_${package_name}.py`. This will guarantee that when any program in any package that was *generated from* the source `${package_name}` package crashes, the hook will be triggered. Although we could potentially create symlinks for `source_cc-shim.py`, `source_cc-proxy.py` and `source_qemu-lite.py`, that might be actually rather tricky due to the package dependencies: the runtime depends on the other elements rather than the other way round. If the elements depended on the runtime, it would be easy for each package to create a sym-link to `source_cc-runtime.py` as that package would have already installed its apport hook. However, that isn't possible currently.

As such, and since it is such a simple script that probably won't change, I think the best solution is to simply copy the hook to the different packages and give it the correct name. The packaging scripts could still have a single copy of the hook and create it with the correct name at package build time of course.

**Comment by jodh-intel** [comment]
Looking at this a little more closely, there is a problem... golang doesn't handle signals in the "normal" Unix way. To make the golang runtime dtrt for apport requires setting a "magic env-var": `GOTRACEBACK=crash`. The problem is, setting it inside a program (even in `init`) is too late - it won't have any effect. We can arrange for this to be set for the proxy (in the unit file), but we can't really do this for the runtime. The hypervisor and the shim are fine as they are conventional C programs so the apport hook will dtrt.

@sboeuf - any thoughts on `GOTRACEBACK`?

**Comment by sboeuf** [comment]
@jodh-intel `GOTRACEBACK` sounds fine to me :)

**Comment by jodh-intel** [comment]
Problem resolved - I found the required knob to enable without relying on the env-var (see referenced PRs for runtime and proxy).

@gorozco1, @erick0z - do you think we could get this hook added to the next release?

**Comment by gorozco1** [comment]
@jodh-intel I am wondering why this change is so ubuntu specific. o.O
