### ISSUE TITLE
Update linux-container kernel

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#165]
We're currently using `linux-container-4.9.54-78` (from https://github.com/clearcontainers/packaging/blob/master/versions.txt#L8). However, the latest standard kernel in clr is much newer (`4.13.8-424`):

- https://github.com/clearlinux-pkgs/linux/blob/master/linux.spec

See also:

- https://github.com/clearlinux-pkgs/linux-container/blob/master/linux-container.spec

@sameo, @grahamwhaley, @devimc, @jcvenegas, @mcastelino - is there any reason we need to stay on `4.9`?

**Comment by jodh-intel** [comment]
If we're not blocked on `4.9`, we should consider updating the kernel package for each weekly release.

**Comment by grahamwhaley** [comment]
@jodh-intel iirc, for the container kernel we stick to the most recent 'longterm' kernel, which right now is 4.9.57 (so we are due a small update there by the look of it). The main Clear Linux kernel sticks to the latest 'stable' kernel, which is 4.13.8 - hence, the disparity. We predominantly do this to reduce the number of updates we'd have to roll out - Clear Linux is on a daily build/release (rolling) cycle, so can track the daily updates to 'stable' pretty well. We are more of a weekly cadence for Clear Containers, so cope better tracking the (less frequent) critical fixes and updates that come from the 'longterm' kernel series.
/cc @miguelinux as well.

**Comment by jodh-intel** [comment]
Right. We *really* need to have this written down in a central location so we (well maybe just me :) don't forget.

@jcvenegas - can you take a look at doing this with @gorozco1 on https://github.com/clearcontainers/runtime/issues/632 ?

**Comment by mcastelino** [comment]
@amshinde @miguelinux as part of doing this update, we should include VFIO support within the Clear Containers kernel. This will ensure the VFIO can also be used within the Clear Container, with device assignment, in the same manner as it would be used in the case of runc.

**Comment by jodh-intel** [comment]
https://www.kernel.org/ is showing that the latest LTS kernel is now `4.9.58` whilst the container kernel is still on `4.9.54`.

@miguelinux, @jcvenegas - is there a plan to update to this version for clr?

**Comment by miguelinux** [comment]
@jodh-intel it is updated, only needs to be public

see https://github.com/clearcontainers/linux/tree/v4.9.58.79-clearcontainers

**Comment by jodh-intel** [comment]
Thanks @miguelinux ! :smile:

**Comment by gorozco1** [comment]
Fixed with #173
