### ISSUE TITLE
opensuse: cc-shim and cc-runtime out of sync while upgrading

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/packaging#180]
Problem: nothing provides cc-shim >= 3.0.6+git.11b5eef-11.1 needed by cc-runtime-3.0.6+git.549ba28-11.1.x86_64

**Comment by erick0z** [comment]
@gorozco1 Which version of openSUSE are you running? I've just tested with openSUSE Leap 42.3 and it does install the packages except for qemu-lite, which is not building right now. Maybe updating the cache?

**Comment by gorozco1** [comment]
@thiagomacieira has the details and was while upgrading...

**Comment by thiagomacieira** [comment]
The issue was in the "staging" repository - https://build.opensuse.org/project/show/home:clearcontainers:clear-containers-3-staging. There, shim is still 3.0.5, while runtime and proxy are 3.0.6.

After switching to the non-staging, it's working.

**Comment by erick0z** [comment]
@thiagomacieira Cool! BTW, we are moving to local testing (using osc build) prior releasing to "non-staging" and we'll probably deprecate "staging".

**Comment by erick0z** [comment]
I think we can close this one.
