### ISSUE TITLE
Package ksm-throttler

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#198]
Now that https://github.com/kata-containers has launched, we need to package its https://github.com/kata-containers/ksm-throttler for Clear Containers systems.

For the last packaged version of the proxy, it ran as a system service under `systemd`. However, now that https://github.com/clearcontainers/runtime/pull/835 has landed, the runtime will launch a proxy instance for each VM. This makes the system level proxy redundant.

But there is more too it than that: since the proxy was running at the system level, it could also manage the KSM settings when new VM's where launched. However, that is not possible now there are potentially multiple VM-specific proxies running on a system.

The result is that by moving the proxy down to the VM level, we've lost the ability to apply KSM settings *using the proxy*. For this reason, the `ksm-throttler` was created that will run as a system service and replace the KSM responsibilities that used to be performed by the system-level proxy.

# Summary

- We need to package `ksm-throttler` and make it install for the next Clear Containers release to re-introduce the KSM feature.
- We need to remove the `cc-proxy` systemd service and socket files in the packaging since `cc-proxy` is no longer needed as a system-level service.

# See

- https://github.com/clearcontainers/runtime/issues/795

**Comment by jodh-intel** [comment]
Note that I think the packaging scripts will also need to do something like the following:

```
 $ sudo systemctl stop cc-proxy.socket
 $ sudo systemctl stop cc-proxy.service
 $ sudo rm /lib/systemd/system/cc-proxy.socket
 $ sudo rm /lib/systemd/system/cc-proxy.service
 $ sudo systemctl daemon-reload
```

**Comment by erick0z** [comment]
@jodh-intel Yeah, the service/socket files can be removed in a post-install script when installing the new proxy package. I'll open a separate issue for that. Thanks!
