### ISSUE TITLE
Update Clear Linux packaging to 3.0.10

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#205]
Whilst looking at https://github.com/clearcontainers/runtime/issues/825, I noticed that clr is still on 3.0.8:

- https://github.com/clearlinux-pkgs/clear-containers-runtime/blob/master/clear-containers-runtime.spec

@jcvenegas - do you think we can find a way to trigger an update to the clr packages when we create updated packages for the other distros?

**Comment by jcarlosv** [comment]
It was suppose to be automated, all the CC packages compatible with autospec, let me check.

**Comment by jodh-intel** [comment]
@jcarlosv - thanks!

**Comment by jcvenegas** [comment]
@jodh-intel I am not sure why was not updated, but just check and now was updated by CL team, next build should provide last CC.

**Comment by jodh-intel** [comment]
Odd - yes, I see now that the spec file was updated 3 days ago so maybe an issue with the infrastructure that pushes those changes to the github repo referenced in the original description.

Can you do a manual check for the next CC release "just in case" to ensure Clr stays current?

**Comment by jcvenegas** [comment]
@jodh-intel just check, CC last version is intalled in last CL release.

**Comment by jodh-intel** [comment]
@jcvenegas - https://github.com/clearlinux-pkgs/clear-containers-runtime/blob/master/clear-containers-runtime.spec is showing `3.0.10` but shouldn't that be `3.0.11` now?
