### ISSUE TITLE
need to specify version dependencies for CC components

### ISSUE THREAD

**Issue by egernst** [clearcontainers/packaging#21]
We don't have version checks for the dependent components.

When I do an initial install of clear containers, I simply run "apt-get install cc-oci-runtime", thereby pulling all the dependent packages.

Now, when I do a major update (let's say 2.1 to 2.2 for this particular example), there are many changes and hard dependencies introduced for Clear Containers Image, kernel version and the runtime.  However, when I do apt-get install cc-oci-runtime to pull latest, only the runtime is updated.  I think this would be resolved if we had version checks in the package, instead of just a dependency.  See below:

```
root@s2rf6n2:/tmp/cc-oci-runtime# dpkg -I  /var/cache/apt/archives/cc-oci-runtime_2.2.2+git.9953d80-31.1_amd64.deb                   
 new debian package, version 2.0.
 size 1615746 bytes: control archive=1025 bytes.
     596 bytes,    11 lines      control
     846 bytes,    12 lines      md5sums
     154 bytes,     6 lines   *  postinst             #!/bin/bash
 Package: cc-oci-runtime
 Version: 2.2.2+git.9953d80-31.1
 Architecture: amd64
 Maintainer: clearlinux.org team <dev@lists.clearlinux.org>
 Installed-Size: 6975
 Depends: libc6 (>= 2.14), libglib2.0-0 (>= 2.43.1), libjson-glib-1.0-0 (>= 0.16.0), libmnl0 (>= 1.0.3-4~), libuuid1 (>= 2.16), qemu-lite, clear-containers-image, linux-container
 Section: devel
 Priority: optional
 Homepage: https://clearlinux.org/features/clear-containers
 Description:
  An Open Containers Initiative (OCI) "runtime" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
```

**Comment by egernst** [comment]
@jcvenegas @gorozco1 @erick0z

**Comment by egernst** [comment]
@chavafg , @GabyCT  -- I'm wondering how this could be handled by QA, or if you do a clean install from scratch each time?  I think we should make sure we hit the upgrade path (correct me if I"m doing something wrong).  Thx!

**Comment by chavafg** [comment]
Currently we do something like this: 
```
UBUNTU_PKGS="clear-containers-image linux-container qemu-lite cc-oci-runtime"
eval sudo apt -y install "$UBUNTU_PKGS" --upgrade 
```
But you are correct, you shouldn't need to specify all the packages. Will add a test for this scenario once it is fixed.

**Comment by egernst** [comment]
@chavafg @gorozco1 @erick0z  -- ETA for fixing this issue?

**Comment by gorozco1** [comment]
@egernst Good catch, let me take a look and see how we can automate the versions dependencies too.

**Comment by erick0z** [comment]
I'm working on this PR (https://github.com/01org/cc-oci-runtime/pull/1042) which solves the issue for CC 2.X. I will send a similar PR to this repository which is used for CC 3.X.
