### ISSUE TITLE
OBS kernel config file doesn't match in-repo config

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#213]
As mentioned [here](https://github.com/clearcontainers/packaging/issues/207#issuecomment-351840531), I think that https://github.com/clearcontainers/packaging/blob/master/kernel/kernel-config-4.9.x is the "master kernel config file".

Somehow, that file gets converted to `./config` for the files below to use:

- https://github.com/clearcontainers/packaging/blob/master/kernel/debian.rules
- https://github.com/clearcontainers/packaging/blob/master/kernel/linux-container.spec-template

Since those files get used in an [OBS environment](https://build.opensuse.org/) and since I can't find any mention of `config` in this repo, and since the OBS config file hasn't been changed for ~1 month, it looks like we might have a manual process to upload https://github.com/clearcontainers/packaging/blob/master/kernel/kernel-config-4.9.x to:

- https://build.opensuse.org/package/view_file/home:clearcontainers:clear-containers-3/linux-container/config

We need to find a way to automate that upload to ensure the two copies of the file are identical - currently they are different:

```diff
--- kernel/kernel-config-4.9.x	2017-12-11 12:13:12.730785110 +0000
+++ /tmp/config.obs	2017-12-14 21:39:58.948167953 +0000
@@ -35,7 +35,6 @@
 CONFIG_AUDIT_ARCH=y
 CONFIG_ARCH_SUPPORTS_OPTIMIZED_INLINING=y
 CONFIG_ARCH_SUPPORTS_DEBUG_PAGEALLOC=y
-CONFIG_HAVE_INTEL_TXT=y
 CONFIG_X86_64_SMP=y
 CONFIG_ARCH_SUPPORTS_UPROBES=y
 CONFIG_FIX_EARLYCON_MEM=y
@@ -456,7 +455,6 @@
 CONFIG_PHYS_ADDR_T_64BIT=y
 CONFIG_BOUNCE=y
 CONFIG_VIRT_TO_BUS=y
-CONFIG_MMU_NOTIFIER=y
 CONFIG_KSM=y
 CONFIG_DEFAULT_MMAP_MIN_ADDR=4096
 # CONFIG_TRANSPARENT_HUGEPAGE is not set
@@ -601,10 +599,9 @@
 # CONFIG_PCI_REALLOC_ENABLE_AUTO is not set
 # CONFIG_PCI_STUB is not set
 # CONFIG_HT_IRQ is not set
-CONFIG_PCI_ATS=y
 # CONFIG_PCI_IOV is not set
 # CONFIG_PCI_PRI is not set
-CONFIG_PCI_PASID=y
+# CONFIG_PCI_PASID is not set
 CONFIG_PCI_LABEL=y
 CONFIG_HOTPLUG_PCI=y
 CONFIG_HOTPLUG_PCI_ACPI=y
@@ -1340,9 +1337,9 @@
 # CONFIG_IGBVF is not set
 # CONFIG_IXGB is not set
 CONFIG_IXGBE=y
-CONFIG_IXGBEVF=y
-CONFIG_I40E=y
-CONFIG_I40EVF=y
+# CONFIG_IXGBEVF is not set
+# CONFIG_I40E is not set
+# CONFIG_I40EVF is not set
 # CONFIG_FM10K is not set
 # CONFIG_NET_VENDOR_I825XX is not set
 # CONFIG_JME is not set
@@ -1733,15 +1730,6 @@
 # CONFIG_SYNC_FILE is not set
 # CONFIG_AUXDISPLAY is not set
 # CONFIG_UIO is not set
-CONFIG_VFIO_IOMMU_TYPE1=y
-CONFIG_VFIO_VIRQFD=y
-CONFIG_VFIO=y
-CONFIG_VFIO_NOIOMMU=y
-CONFIG_VFIO_PCI=y
-CONFIG_VFIO_PCI_MMAP=y
-CONFIG_VFIO_PCI_INTX=y
-CONFIG_VFIO_PCI_IGD=y
-CONFIG_IRQ_BYPASS_MANAGER=y
 CONFIG_VIRT_DRIVERS=y
 CONFIG_VIRTIO=y
 
@@ -1800,20 +1788,7 @@
 # CONFIG_SH_TIMER_TMU is not set
 # CONFIG_EM_TIMER_STI is not set
 # CONFIG_MAILBOX is not set
-CONFIG_IOMMU_API=y
-CONFIG_IOMMU_SUPPORT=y
-
-#
-# Generic IOMMU Pagetable Support
-#
-CONFIG_IOMMU_IOVA=y
-# CONFIG_AMD_IOMMU is not set
-CONFIG_DMAR_TABLE=y
-CONFIG_INTEL_IOMMU=y
-CONFIG_INTEL_IOMMU_SVM=y
-CONFIG_INTEL_IOMMU_DEFAULT_ON=y
-CONFIG_INTEL_IOMMU_FLOPPY_WA=y
-CONFIG_IRQ_REMAP=y
+# CONFIG_IOMMU_SUPPORT is not set
 
 #
 # Remoteproc drivers
@@ -2231,7 +2206,6 @@
 # CONFIG_SECURITYFS is not set
 # CONFIG_SECURITY_NETWORK is not set
 # CONFIG_SECURITY_PATH is not set
-# CONFIG_INTEL_TXT is not set
 CONFIG_HAVE_HARDENED_USERCOPY_ALLOCATOR=y
 CONFIG_HAVE_ARCH_HARDENED_USERCOPY=y
 # CONFIG_HARDENED_USERCOPY is not set
@@ -2294,7 +2268,7 @@
 CONFIG_CRYPTO_CBC=y
 CONFIG_CRYPTO_CTR=y
 # CONFIG_CRYPTO_CTS is not set
-CONFIG_CRYPTO_ECB=y
+# CONFIG_CRYPTO_ECB is not set
 CONFIG_CRYPTO_LRW=y
 # CONFIG_CRYPTO_PCBC is not set
 CONFIG_CRYPTO_XTS=y
```

Presumably, we can tweak `kernel/update_kernel.sh` to upload https://github.com/clearcontainers/packaging/blob/master/kernel/kernel-config-4.9.x to https://build.opensuse.org/package/view_file/home:clearcontainers:clear-containers-3/linux-container/config.

Short-term, we need to get the OBS config file synced (manually or otherwise) to ensure we're building with the correct kernel config).

/cc @grahamwhaley, @mcastelino.

**Comment by erick0z** [comment]
@jodh-intel I got the issue. When the `checkout_repo` function is called in the update_kernel.sh, it does `cp ${GENERATED_FILES[@]} $OBS_WORKDIR`, but `config` is not listed in the `GENERATED_FILES` array (shame on me!). I think I messed up when refactored all the setup scripts.

**Comment by amshinde** [comment]
There were changes related to VFIO that were introduced in our agent, that rely on recent kernel config changes that are missing. I am afraid we may be broken because of this.
@erick0z  We should generate and release a new kernel package asap.

**Comment by grahamwhaley** [comment]
@chavafg @amshinde - is that showing a gap in our QA maybe?

**Comment by jodh-intel** [comment]
@erick0z - don't be too hard on yourself - everyone makes mistakes! :smile: In fact, we **all** share the responsibility and should have picked this up at the review stage.

@amshinde is right, but I see that you've now re-uploaded the `config` and re-generated the packages, so thanks for doing that.

FTR, the diff between `kernel/kernel-config-4.9.x` and the `config` in http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/Fedora_26/src/linux-container-4.9.60-81.1.src.rpm is just:

```diff
diff kernel/kernel-config-4.9.x /tmp/linux-container-4.9.60-81.1.src.rpm.config 
3c3
< # Linux/x86 4.9.54 Kernel Configuration
---
> # Linux/x86_64 4.9.60 Kernel Configuration
```
