### ISSUE TITLE
No dependency to install ksm-throttler 

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#225]
I've just updated a test box to https://github.com/clearcontainers/runtime/releases/tag/3.0.12, but noticed that although #200 has landed, I don't have the ksm throttler installed.

I have manually `apt-get install`'ed it but also needed to do the following to get it working:

```
$ sudo systemctl enable cc-ksm-throttler
$ sudo systemctl start cc-ksm-throttler
```

I think we need to make one of the other packages depend on this to have it auto-installed and also auto-enabled and started.

@sameo, @grahamwhaley - do you agree?

By the way, it's great to see the renaming works nicely! :smile::

```
$ sudo journalctl -t cc-ksm-throttler|grep level=
Dec 22 11:14:08 zesty cc-ksm-throttler[17412]: time="2017-12-22T11:14:08Z" level=info name=cc-ksm-throttler pid=17412 source=throttler version=0.0.1
Dec 22 11:14:08 zesty cc-ksm-throttler[17412]: time="2017-12-22T11:14:08Z" level=debug msg="Starting KSM throttling service at /var/run/cc-ksm-throttler/ksm.sock" name=cc-ksm-throttler pid=17412 source=throttler
```

**Comment by grahamwhaley** [comment]
I would think we want it installed and enabled by default with CC, yes.
How that is done in the packaging itself I think yourself and @erick0z will know how :-)

**Comment by erick0z** [comment]
@jodh-intel @grahamwhaley I can make it a dependency of cc-runtime (like everything else) in order to have it enabled by default.

**Comment by jodh-intel** [comment]
Thanks @erick0z.

@chavafg, @grahamwhaley  - once that lands, we'll need to ensure the CI, test and PnP systems disable it (unless they are explicitly testing the throttler itself).
