### ISSUE TITLE
Create Fedora 27 OBS packages

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#230]
Now that docker supports F27, we need to start creating Fedora 27 OBS binaries.

See:

- https://download.docker.com/linux/fedora/27/x86_64/stable/Packages/
- https://github.com/clearcontainers/runtime/issues/882

**Comment by erick0z** [comment]
@jodh-intel I've added Fedora 27 packages. Thanks!

**Comment by jodh-intel** [comment]
@erick0z - thanks!

**Comment by erick0z** [comment]
since Fedora 27 packages are already available in OBS (https://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/Fedora_27/). I think we can close this one.
