### ISSUE TITLE
Container selinux dependency not working on RHEL

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/packaging#249]
While trying to install the OBS packages for RHEL, the container selinux is not working properly
Install Clear Containers components and their dependencies

site="http://download.opensuse.org"
dir="repositories/home:/clearcontainers:/clear-containers-3/ RHEL_7"
repo_file="home:clearcontainers:clear-containers-3.repo"
cc_repo_url="${site}/${dir}/${repo_file}"

sudo yum-config-manager --add-repo "${cc_repo_url}"
sudo yum -y install cc-runtime cc-proxy cc-shim linux-container clear-containers-image

However, I am getting this error….

Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
clear-containers-selinux-0.1-4 FAILED
http://download.opensuse.org/repositories/home%3A/clearcontainers%3A/clear-containers-3/RHEL_7/noarch/clear-containers-selinux-0.1-4.2.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found- ETA
Trying other mirror.
To address this issue please refer to the below knowledge base article

**Comment by erick0z** [comment]
Hi @GabyCT, I did a version bump of the package. Can you try again with `sudo yum clean all; sudo yum install cc-runtime`.

**Comment by GabyCT** [comment]
Hi @erick0z thanks for fixing this...
Running transaction
  Installing : cc-runtime-config-3.0.14+git.753dfa1-19.1.x86_64                                                                                                                          1/11
  Installing : cc-runtime-bin-3.0.14+git.753dfa1-19.1.x86_64                                                                                                                             2/11
  Installing : linux-container-4.9.60-84.1.x86_64                                                                                                                                        3/11
  Installing : cc-shim-bin-3.0.14+git.3b5e854-19.1.x86_64                                                                                                                                4/11
  Installing : cc-shim-3.0.14+git.3b5e854-19.1.x86_64                                                                                                                                    5/11
  Installing : cc-proxy-bin-3.0.14+git.061d5dc-19.1.x86_64                                                                                                                               6/11
  Installing : cc-ksm-throttler-0.0.1.git+fd007ea-2.1.x86_64                                                                                                                             7/11
  Installing : clear-containers-selinux-0.1-5.1.noarch                                                                                                                                   8/11
  Installing : cc-proxy-3.0.14+git.061d5dc-19.1.x86_64
