### ISSUE TITLE
move QEMU from pc-lite to pc machine type

### ISSUE THREAD

**Issue by egernst** [clearcontainers/packaging#25]
Make QEMU configurable between PC and PC-Lite machine types.

**Comment by gorozco1** [comment]
Currently our packaged qemu-lite is created from:

https://github.com/01org/qemu-lite

We need to move to use this:

https://github.com/clearcontainers/qemu/tree/qemu-lite-v2.9.0


From: https://github.com/clearcontainers/tests/blob/master/.ci/setup_env_ubuntu.sh

./configure --disable-tools --disable-libssh2 --disable-tcmalloc --disable-glusterfs 
--disable-seccomp --disable-{bzip2,snappy,lzo} --disable-usb-redir --disable-libusb 
--disable-libnfs --disable-tcg-interpreter --disable-debug-tcg --disable-libiscsi 
--disable-rbd --disable-spice --disable-attr --disable-cap-ng --disable-linux-aio 
--disable-brlapi --disable-vnc-{jpeg,png,sasl} --disable-rdma --disable-bluez 
--disable-fdt --disable-curl --disable-curses --disable-sdl --disable-gtk 
--disable-tpm --disable-vte --disable-vnc --disable-xen --disable-opengl 
--disable-slirp --enable-trace-backend=nop --enable-virtfs --enable-attr 
--enable-cap-ng --target-list=x86_64-softmmu

**Comment by egernst** [comment]
done already.
