### ISSUE TITLE
packages: Use osbuilder image instead of Clear Linux

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/packaging#261]
Instead of use Clear Linux images use an image from https://github.com/clearcontainers/osbuilder/releases based on the agent version and CL image defined in versions.txt file from runtime

**Comment by jcvenegas** [comment]
Image already tesed here https://github.com/clearcontainers/tests/pull/839 .

**Comment by jodh-intel** [comment]
`osbuilder` rocks! :smile:
