### ISSUE TITLE
Test upgradability from 2.1 to 3.0

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/packaging#32]
We need a way to make sure clear containers 2.x can be upgrade to 3.x for `debian` based distros and `redhat` based distros

**Comment by gorozco1** [comment]
@GabyCT or @chavafg is this something you can take ?

**Comment by gorozco1** [comment]
@MarioCarrilloA please add the comments you have related to this issue here.

**Comment by jodh-intel** [comment]
Related: https://github.com/clearcontainers/runtime/pull/546 (which adds a `docs/upgrading.md` document, including some tweaks necessary (I think) to allow for successful upgrades).
