### ISSUE TITLE
cc-runtime: Does not build on RHEL systems due glibc-static package missing

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/packaging#38]
RHEL does not provide `glibc-static`.

**Comment by erick0z** [comment]
I tried to use the glibc-static libraries from CentOS 7 during the build time with no luck. Extracted the rpm and placed the libraries in the buildroot-dir ```home/abuild/rpmbuild/BUILD/tmp/usr/lib64/``` and ```LIBRARY_PATH``` pointing to it.

The following error showed up:
```
# github.com/clearcontainers/runtime/vendor/github.com/vishvananda/netlink
[   65s] /bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/home/abuild/rpmbuild/BUILD/tmp/usr/lib64/../lib64/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie
[   65s] collect2: error: ld returned 1 exit status
```
It seems glibc-static needs to be recompiled, in the best scenario.
So, if we are going to deal with custom packages anyway, why we don't just use the CentOS 7 OBS packages?. It is supposed to be compatible with RHEL and the packages are ready to be used.

**Comment by grahamwhaley** [comment]
Just to clarify here - this is actually a failure to build the golang `cc-runtime` program, yes?
Can we get a bit more of the logs for the build fail when `glibc-static` is not installed as well, just for more clarity.
Odd that they exist on Centos and not RHEL. Do we have a link to be able to browse the package list on RHEL (maybe that is only available if you are a paying customer??).

**Comment by gorozco1** [comment]
@grahamwhaley with RHEL we had do try workarounds ie:

* rpm2cpio glibc-static | cpio -idmv  and then using the library extracted to build pause.  (that was our first try).

Then build `cc-runtime` without pause and that error came up.

Apparently build static binaries is forbidden in rhel and the `glibc` in RHEL is not compiled to support static binaries. 

@erick0z Could you please submit your PR to link to this issue to take a look a the changes? we'll need to tag the PR with  the `do-not-merge` tag

**Comment by jodh-intel** [comment]
Related https://github.com/clearcontainers/runtime/pull/372.

**Comment by erick0z** [comment]
@grahamwhaley The pause binary is compiled before the runtime and I think it could be the culprit, I will keep digging. The ```glibc-static``` package actually exists on RHEL but it is part of some sort of "extra-packages" that are only available through subscription, OBS does not include these. And no, I don't have that packages list :(

**Comment by jodh-intel** [comment]
If it is purely for the `pause` binary, I'm wondering why we can't just rewrite it in go - it's tiny and only makes a few calls. @sboeuf - any view on this?

**Comment by sboeuf** [comment]
@jodh-intel Of course, I have no objection about re-writing the pause binary in Go.

**Comment by jodh-intel** [comment]
@erick0z - right, if you can prove we only need static libs for the pause binary, we'll rewrite the pause binary in go to make the problem "go away" ;-)

**Comment by gorozco1** [comment]
@wcwxyz do you have any clue on why https://github.com/containers/virtcontainers needed `pause` written in C?

**Comment by sboeuf** [comment]
@gorozco1 We didn't *need* this pause binary to be written in C, it is just that we did a copy/paste from CRI-O as they are using the same trick with the "pause" container. But basically, I don't care the way it is written because this is a binary that we provide from the host to the VM, meaning it can be any size, it won't affect the footprint of the VM.

**Comment by wcwxyz** [comment]
@gorozco1 I don't know. I'm not author. But I think if it's written in go, it would still need glibc-static.

**Comment by wcwxyz** [comment]
@sboeuf I know docker doesn't need pause container. Does CRI-O need to pause container?

Anyway I see https://github.com/containers/virtcontainers/issues/225, it says hyperstart now supports to keep pod alive. Maybe it's time to remove pause.

**Comment by sboeuf** [comment]
@wcwxyz Yes CRI-O uses an infrastructure container (basically a pause container) to run the concept of pod. Regarding Clear Containers, we will keep this around since we're not following hyperstart upstream. And we're actually moving to our own agent, but this does not mean that we won't get rid of this pause container someday :)

**Comment by erick0z** [comment]
@jodh-intel Sorry, OBS was b0rked yesteday. I tried to build the runtime with a small patch that ignores the build of the pause binary and without the glibc-static libraries and it actually builds the runtime.
```
+ tree /home/abuild/rpmbuild/BUILDROOT/cc-runtime-3.0.0alpha.4+git.7e3b6bf-29.1.x86_64
[   69s] /home/abuild/rpmbuild/BUILDROOT/cc-runtime-3.0.0alpha.4+git.7e3b6bf-29.1.x86_64
[   69s] |-- etc
[   69s] |   `-- clear-containers
[   69s] |       `-- configuration.toml
[   69s] `-- usr
[   69s]     `-- bin
[   69s]         `-- cc-runtime
[   69s] 
```

You can see the full log here: https://build.opensuse.org/package/live_build_log/home:erick0zcr/cc-runtime/RHEL_7/x86_64
And the spec file: https://build.opensuse.org/package/view_file/home:erick0zcr/cc-runtime/cc-runtime.spec?expand=1

**Comment by jodh-intel** [comment]
Blocked on https://github.com/clearcontainers/runtime/pull/434.

**Comment by jodh-intel** [comment]
Hi @gorozco1, @erick0z  - now that https://github.com/clearcontainers/runtime/pull/434 has landed, are we able to build packages for RHEL?

**Comment by erick0z** [comment]
@jodh-intel Yes, it's now building!

**Comment by jodh-intel** [comment]
Great - I'm not seeing the rpms yet?

**Comment by gorozco1** [comment]
@jodh-intel the rpms are in the staging repo (ready to be tested)  

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3-staging/RHEL_7/x86_64/

Remember that in rhel, centos and sles qemu-lite is not building. So it needs to be build by hand.

**Comment by gorozco1** [comment]
Closing this issue due: https://github.com/clearcontainers/runtime/pull/434
