### ISSUE TITLE
Update components to 3.0.0-beta.1

### ISSUE THREAD

**Issue by erick0z** [clearcontainers/packaging#58]
This issue is raised in order to track the update of the following components.

Components that will be updated to 3.0.0-beta.1:
- runtime
- proxy

**Comment by gorozco1** [comment]
What about qemu-cc

**Comment by erick0z** [comment]
@gorozco1 I'm waiting for https://github.com/clearcontainers/packaging/pull/34 to be merged.

**Comment by gorozco1** [comment]
@erick0z you're right `qemu-cc` not approved for beta1 release 👍
