### ISSUE TITLE
missing packages linux-container and qemu-lite for OpenSUSE in OBS repo

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/packaging#60]
The packages repo is missing `linux-container` and `qemu-lite` packages needed to run Clear Containers in OpenSUSE

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/openSUSE_Tumbleweed/

**Comment by erick0z** [comment]
@gorozco1 Do we really want to have Tumbleweed as build target? I mean, it is a rolling release distro. If we want to support Opensuse, I think Leap 42.3 should be the build target.

**Comment by gorozco1** [comment]
@erick0z we do a number of SuSE based distros.

SLE_12/              
SLE_12_SP1/          
SLE_12_SP2/          
SLE_12_SP3/          
openSUSE_Leap_42.2/  
openSUSE_Leap_42.3/  
openSUSE_Tumbleweed/

**Comment by erick0z** [comment]
Note: openSUSE is not on the docker store and the packages for openSUSE Leap 42.3 have docker in version 1.12.6-31.15 (not docker-ce).

**Comment by gorozco1** [comment]
closed in favor of: #62
