### ISSUE TITLE
kernel v4.9.35-76-clearcontainers does not privide config

### ISSUE THREAD

**Issue by jcvenegas** [clearcontainers/packaging#69]
There is not clear containers config in kernel /v4.9.35-76-clearcontainers from github.com/clearcontainers/linux

**Comment by miguelinux** [comment]
@jcvenegas I already add it to containers/linux

Could you verify this?

**Comment by jcvenegas** [comment]
@miguelinux yes it having?  just one question, will  `.config` be the default path for  https://github.com/clearcontainers/linux? I ask because I am updating osbuilder to build the latest kernel and dont want it is breaked in the future.

**Comment by miguelinux** [comment]
It is done at

https://github.com/clearcontainers/linux/commit/104060c03e0ef4fe56d1ed5b21f4f0ce8f78001b

The default will be **arch/x86/configs/clear_containers_defconfig**
