### ISSUE TITLE
ubuntu: cc-runtime --version does not show commit ID 

### ISSUE THREAD

**Issue by chavafg** [clearcontainers/packaging#89]
On ubuntu, there is no information about the commit ID, while in Fedora you have this information.

```
cloud@ubuntu1604-obs-cc3:~/go/src/github.com/clearcontainers/tests$ cc-runtime --version
cc-runtime  : 3.0.0-beta.1
   OCI specs: 1.0.0-rc5
```

**Comment by jodh-intel** [comment]
This suggests that the `commit` variable in the file `config-generated.go` is set to `""`. That could happen if the runtime build is not run in the runtime `git` tree.
