### ISSUE TITLE
cc-runtime package should conflict with cc-oci-runtime package

### ISSUE THREAD

**Issue by jodh-intel** [clearcontainers/packaging#93]
If a user attempts to install CC 3.0 on a system with CC 2.1, this happens:

- https://github.com/clearcontainers/runtime/issues/495#issuecomment-326688692

We should make the `cc-runtime` package conflict with the `cc-oci-runtime` one so that `yum`/`dnf`/`apt` know to remove `cc-oci-runtime` when the user requests installation of `cc-runtime`.

Since with CC 2.1 the `cc-oci-runtime` package contains `cc-proxy` and `cc-shim`, this will result in the CC 2.1 versions of the proxy+shim being removed. This is the desired behaviour since the CC 2.1 versions of those components are incompatible with the CC 3.0 versions.

**Comment by gorozco1** [comment]
This should be fixed EOW

**Comment by jodh-intel** [comment]
If this is fixed before release, we need to remove the text, "IMPORTANT: Do not combine Clear Containers 2.1 and Clear Containers 3.0. Both projects ship cc-proxy and they are not compatible with each other." from:

- https://github.com/clearcontainers/runtime/blob/master/docs/developers-clear-containers-install.md

If this isn't fixed before release, we need to add the warning to:

- https://github.com/clearcontainers/runtime/blob/master/docs/fedora-installation-guide.md
- https://github.com/clearcontainers/runtime/blob/master/docs/ubuntu-installation-guide.md

**Comment by jodh-intel** [comment]
In fact, I wonder if instead we want to create a generic "upgrade statement" document that outlines:

- what is possible / supported
- what is not possible / supported (such as CC 2.1 config is not converted to 3.0 for example).

If it is couched in non-OS-specific terms, we can avoid the duplication across multiple docs and get the install docs to reference it.

@sameo, @grahamwhaley, @iphutch - what do you think?

**Comment by gorozco1** [comment]
agree

**Comment by iphutch** [comment]
Agree. Great idea. Any way we can avoid having to maintain duplicated docs - I'm all for it.

**Comment by jodh-intel** [comment]
ok, I've raised https://github.com/clearcontainers/runtime/issues/528 to create such a document.
